"""cuenta de google vinculada por usuario

Revision ID: 202880d66344
Revises: d6c632069ed4
Create Date: 2026-09-13 17:44:08.676349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202880d66344'
down_revision = 'd6c632069ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuenta_google',
    sa.Column('id_cuenta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('correo_google', sa.String(length=150), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('fecha_conexion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cuenta'),
    sa.UniqueConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuenta_google')
    # ### end Alembic commands ###
