"""esquema inicial

Revision ID: b2dfee22bcd7
Revises: 
Create Date: 2026-09-09 22:49:09.694749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dfee22bcd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ficha', sa.String(length=30), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_curso')
    )
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('persona_contacto', sa.String(length=100), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('numero_documento', sa.String(length=30), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('aprendiz',
    sa.Column('id_aprendiz', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('ficha', sa.String(length=30), nullable=True),
    sa.Column('estado_practica', sa.String(length=30), nullable=True),
    sa.Column('horas_requeridas', sa.Integer(), nullable=True),
    sa.Column('horas_cumplidas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_aprendiz'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('historial_cambios',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.Column('accion', sa.Enum('CREAR', 'MODIFICAR', 'ELIMINAR', name='accion_enum'), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_table('instructor',
    sa.Column('id_instructor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('area_formacion', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_instructor'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('notificacion',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    op.create_table('aprendiz_backup',
    sa.Column('id_backup', sa.Integer(), nullable=False),
    sa.Column('id_aprendiz', sa.Integer(), nullable=False),
    sa.Column('datos', sa.Text(), nullable=True),
    sa.Column('fecha_respaldo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_aprendiz'], ['aprendiz.id_aprendiz'], ),
    sa.PrimaryKeyConstraint('id_backup'),
    sa.UniqueConstraint('id_aprendiz')
    )
    op.create_table('curso_aprendiz',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_aprendiz', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_aprendiz'], ['aprendiz.id_aprendiz'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], ),
    sa.PrimaryKeyConstraint('id_curso', 'id_aprendiz')
    )
    op.create_table('curso_instructor',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_instructor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], ),
    sa.ForeignKeyConstraint(['id_instructor'], ['instructor.id_instructor'], ),
    sa.PrimaryKeyConstraint('id_curso', 'id_instructor')
    )
    op.create_table('evidencia',
    sa.Column('id_evidencia', sa.Integer(), nullable=False),
    sa.Column('id_aprendiz', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('archivo', 'enlace', 'texto', name='tipo_evidencia_enum'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('Entregada', 'Revisada', 'Aprobada', 'No Aprobada', name='estado_evidencia_enum'), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('bitacora', sa.String(length=25), nullable=True),
    sa.Column('actas', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['id_aprendiz'], ['aprendiz.id_aprendiz'], ),
    sa.PrimaryKeyConstraint('id_evidencia')
    )
    op.create_table('progreso_aprendiz',
    sa.Column('id_progreso', sa.Integer(), nullable=False),
    sa.Column('id_aprendiz', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_aprendiz'], ['aprendiz.id_aprendiz'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], ),
    sa.PrimaryKeyConstraint('id_progreso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progreso_aprendiz')
    op.drop_table('evidencia')
    op.drop_table('curso_instructor')
    op.drop_table('curso_aprendiz')
    op.drop_table('aprendiz_backup')
    op.drop_table('usuario_rol')
    op.drop_table('notificacion')
    op.drop_table('instructor')
    op.drop_table('historial_cambios')
    op.drop_table('aprendiz')
    op.drop_table('usuario')
    op.drop_table('rol')
    op.drop_table('empresa')
    op.drop_table('curso')
    # ### end Alembic commands ###
