"""fechas de inicio y fin de practica del aprendiz

Revision ID: d6c632069ed4
Revises: b2dfee22bcd7
Create Date: 2026-09-09 23:47:26.574754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c632069ed4'
down_revision = 'b2dfee22bcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aprendiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio_practica', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_fin_practica', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aprendiz', schema=None) as batch_op:
        batch_op.drop_column('fecha_fin_practica')
        batch_op.drop_column('fecha_inicio_practica')

    # ### end Alembic commands ###
